@startuml
actor Customer
Customer -> ConfirmOrderPanel : Place Order
activate ConfirmOrderPanel
ConfirmOrderPanel -> SubscriptionService : create()
activate SubscriptionService
SubscriptionService -> IntegrationService : publish()
activate IntegrationService
IntegrationService -> ISV : e.g. <GET /isv/subscribe>
activate ISV
IntegrationService <- ISV : <GET /integration/v1/events/{TOKEN}>
IntegrationService --> ISV : 200: Event info
IntegrationService <-- ISV : 204: Subscription processed
deactivate ISV
IntegrationService -> SubscriptionOrderCallback : onSuccess()
activate SubscriptionOrderCallback
IntegrationService <-- SubscriptionOrderCallback : Order status updated
deactivate SubscriptionOrderCallback
SubscriptionService <-- IntegrationService : Notified
deactivate IntegrationService
SubscriptionService -> JBillingApi : generateAndPayInvoices()
activate JBillingApi
JBillingApi -> JBillingApiHelper : createInvoice()
activate JBillingApiHelper
JBillingApiHelper -> CreateInvoiceAspect : afterCreateInvoiceAdvice()
activate CreateInvoiceAspect
CreateInvoiceAspect -> JBillingImportService : importInvoice()
activate JBillingImportService
CreateInvoiceAspect <-- JBillingImportService : imported
deactivate JBillingImportService
JBillingApiHelper <-- CreateInvoiceAspect : created
deactivate CreateInvoiceAspect
JBillingApi <-- JBillingApiHelper : created
deactivate JBillingApiHelper
SubscriptionService <-- JBillingApi : Generated
deactivate JBillingApi
ConfirmOrderPanel <-- SubscriptionService : Subscription created
deactivate SubscriptionService
Customer <-- ConfirmOrderPanel : Subscribed
deactivate ConfirmOrderPanel
@enduml
